name: aura_app
description: "Aura - Accessibility app for blind and deaf users"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1

  # ❌ Removed flutter_tts (not supported on Windows)
  # ❌ Removed google_mlkit_object_detection (not supported on Windows/Web)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
